version: '3'

services:
  rss-generator:
    build: .
    container_name: rss-generator
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
    networks:
      - rss_network

networks:
  rss_network:
    driver: bridge 